const theme = {
  colors: {
    primary: {
      100: "#BC1356",
      70: "#BC1356B3",
      40: "#BC135666",
    },
    text: {
      main: "#505050",
      contrasted: "#F8F8F8",
      link: "#00B5DD",
    },
    grey: {
      lightGrey: "#EFEFEF",
      pearlGrey: "#F4F4F4",
      100: "#505050",
      70: "#505050B3",
      40: "#50505066",
      20: "#50505033",
    },
    black: "#000000",
    white: "#FFFFFF",
  },
  fonts: {
    body: [
      "Noto Sans JP",
      "游ゴシック",
      "YuGothic",
      "Avenir",
      "Helvetica neue",
      "Helvetica",
      "ヒラギノ角ゴ Pro W3",
      "Hiragino Kaku Gothic Pro",
      "メイリオ",
      "Meiryo",
      "ＭＳ Ｐゴシック",
      "sans-serif",
    ].join(","),
    heading: [
      "Noto Sans JP",
      "游ゴシック",
      "YuGothic",
      "Avenir",
      "Helvetica neue",
      "Helvetica",
      "ヒラギノ角ゴ Pro W3",
      "Hiragino Kaku Gothic Pro",
      "メイリオ",
      "Meiryo",
      "ＭＳ Ｐゴシック",
      "sans-serif",
    ].join(","),
    mono: [
      "Noto Sans JP",
      "游ゴシック",
      "YuGothic",
      "Avenir",
      "Helvetica neue",
      "Helvetica",
      "ヒラギノ角ゴ Pro W3",
      "Hiragino Kaku Gothic Pro",
      "メイリオ",
      "Meiryo",
      "ＭＳ Ｐゴシック",
      "sans-serif",
    ].join(","),
  },
  fontSizes: {
    sm: "10px",
    md: "12px",
    lg: "14px",
    xl: "16px",
    "2xl": "18px",
    "3xl": "20px",
    "4xl": "22px",
    "5xl": "24px",
    "6xl": "26px",
    "7xl": "28px",
    "8xl": "30px",
    "9xl": "32px",
  },
  fontWeights: {
    hairline: 100,
    thin: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    black: 900,
  },
}

export default theme
